#include "controller/controllerWeather.h"
#include "main.h"
#include <FS.h>
#include <SPIFFS.h>
#include <WiFi.h>

String payload;
HTTPClient httpClient;

#define WEATHER_STUB

#if defined(WEATHER_STUB)
    const String weather_stub = R"YW(
{
  "now": 1726668574,
  "now_dt": "2024-09-18T14:09:34.090037Z",
  "info": {
    "n": true,
    "url": "https://yandex.ru/pogoda/?lat=55.78323&lon=37.47306",
    "lat": 55.78323,
    "lon": 37.47306,
    "tzinfo": {
      "name": "Europe/Moscow",
      "abbr": "MSK",
      "dst": false,
      "offset": 10800
    },
    "def_pressure_mm": 746,
    "def_pressure_pa": 994,
    "zoom": 10,
    "nr": true,
    "ns": true,
    "nsr": true,
    "p": false,
    "f": true,
    "_h": false
  },
  "fact": {
    "daytime": "d",
    "obs_time": 1726668574,
    "season": "autumn",
    "source": "station",
    "uptime": 1726668574,
    "cloudness": 0,
    "condition": "clear",
    "feels_like": 23,
    "humidity": 36,
    "icon": "skc_d",
    "is_thunder": false,
    "polar": false,
    "prec_prob": 0,
    "prec_strength": 0,
    "prec_type": 0,
    "temp": 24,
    "uv_index": 0,
    "wind_angle": 315,
    "wind_dir": "nw",
    "wind_gust": 2,
    "wind_speed": 0.9
  },
  "forecasts": [
    {
      "date": "2024-09-18",
      "date_ts": 1726606800,
      "week": 38,
      "sunrise": "06:07",
      "sunset": "18:40",
      "rise_begin": "05:30",
      "set_end": "19:17",
      "moon_code": 0,
      "moon_text": "moon-code-0",
      "parts": {
        "day": {
          "daytime": "d",
          "_source": "12,13,14,15,16,17",
          "cloudness": 0,
          "condition": "clear",
          "fresh_snow_mm": 0,
          "humidity": 33,
          "icon": "skc_d",
          "polar": false,
          "prec_mm": 0,
          "prec_period": 360,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 25,
          "temp_max": 26,
          "temp_min": 24,
          "feels_like": 24,
          "uv_index": 3,
          "wind_angle": 135,
          "wind_dir": "se",
          "wind_gust": 2.1,
          "wind_speed": 1.3
        },
        "day_short": {
          "daytime": "d",
          "_source": "6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21",
          "cloudness": 0,
          "condition": "clear",
          "fresh_snow_mm": 0,
          "humidity": 49,
          "icon": "skc_d",
          "polar": false,
          "prec_mm": 0,
          "prec_period": 960,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 26,
          "temp_min": 13,
          "feels_like": 21,
          "uv_index": 3,
          "wind_angle": 135,
          "wind_dir": "se",
          "wind_gust": 2.2,
          "wind_speed": 1.3
        },
        "evening": {
          "daytime": "n",
          "_source": "18,19,20,21",
          "cloudness": 0,
          "condition": "clear",
          "fresh_snow_mm": 0,
          "humidity": 47,
          "icon": "skc_n",
          "polar": false,
          "prec_mm": 0,
          "prec_period": 240,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 19,
          "temp_max": 23,
          "temp_min": 16,
          "feels_like": 18,
          "uv_index": 0,
          "wind_angle": 270,
          "wind_dir": "w",
          "wind_gust": 1.8,
          "wind_speed": 0.8
        },
        "morning": {
          "daytime": "d",
          "_source": "6,7,8,9,10,11",
          "cloudness": 0,
          "condition": "clear",
          "humidity": 66,
          "icon": "skc_d",
          "polar": false,
          "prec_period": 360,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 18,
          "temp_max": 23,
          "temp_min": 13,
          "feels_like": 18,
          "uv_index": 2,
          "wind_angle": 45,
          "wind_dir": "ne",
          "wind_gust": 2.2,
          "wind_speed": 1.2
        },
        "night": {
          "daytime": "n",
          "_source": "0,1,2,3,4,5",
          "cloudness": 0,
          "condition": "clear",
          "humidity": 73,
          "icon": "skc_n",
          "polar": false,
          "prec_period": 360,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 13,
          "temp_max": 17,
          "temp_min": 11,
          "feels_like": 12,
          "uv_index": 0,
          "wind_angle": 45,
          "wind_dir": "ne",
          "wind_gust": 1.7,
          "wind_speed": 0.7
        },
        "night_short": {
          "daytime": "n",
          "_source": "0,1,2,3,4,5",
          "cloudness": 0,
          "condition": "clear",
          "humidity": 73,
          "icon": "skc_n",
          "polar": false,
          "prec_period": 360,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 11,
          "feels_like": 12,
          "uv_index": 0,
          "wind_angle": 45,
          "wind_dir": "ne",
          "wind_gust": 1.7,
          "wind_speed": 0.7
        }
      },
      "hours": [
        {
          "hour": "0",
          "hour_ts": 1726606800,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 16,
          "humidity": 61,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 17,
          "uv_index": 0,
          "wind_angle": 155,
          "wind_dir": "se",
          "wind_gust": 1.7,
          "wind_speed": 0.7
        },
        {
          "hour": "1",
          "hour_ts": 1726610400,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 14,
          "humidity": 65,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 15,
          "uv_index": 0,
          "wind_angle": 134,
          "wind_dir": "se",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "2",
          "hour_ts": 1726614000,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 11,
          "humidity": 68,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 97,
          "wind_dir": "e",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "3",
          "hour_ts": 1726617600,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 10,
          "humidity": 81,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 11,
          "uv_index": 0,
          "wind_angle": 28,
          "wind_dir": "ne",
          "wind_gust": 1.4,
          "wind_speed": 0.4
        },
        {
          "hour": "4",
          "hour_ts": 1726621200,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 10,
          "humidity": 82,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 11,
          "uv_index": 0,
          "wind_angle": 28,
          "wind_dir": "ne",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "5",
          "hour_ts": 1726624800,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 11,
          "humidity": 82,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 36,
          "wind_dir": "ne",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "6",
          "hour_ts": 1726628400,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 13,
          "humidity": 82,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 13,
          "uv_index": 0,
          "wind_angle": 32,
          "wind_dir": "ne",
          "wind_gust": 1.4,
          "wind_speed": 0.4
        },
        {
          "hour": "7",
          "hour_ts": 1726632000,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 15,
          "humidity": 81,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 15,
          "uv_index": 0,
          "wind_angle": 49,
          "wind_dir": "ne",
          "wind_gust": 1.5,
          "wind_speed": 0.5
        },
        {
          "hour": "8",
          "hour_ts": 1726635600,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 16,
          "humidity": 76,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 16,
          "uv_index": 0,
          "wind_angle": 39,
          "wind_dir": "ne",
          "wind_gust": 1.5,
          "wind_speed": 0.5
        },
        {
          "hour": "9",
          "hour_ts": 1726639200,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 19,
          "humidity": 64,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 19,
          "uv_index": 1,
          "wind_angle": 78,
          "wind_dir": "e",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "10",
          "hour_ts": 1726642800,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 20,
          "humidity": 51,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 21,
          "uv_index": 2,
          "wind_angle": 122,
          "wind_dir": "se",
          "wind_gust": 2,
          "wind_speed": 1
        },
        {
          "hour": "11",
          "hour_ts": 1726646400,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 22,
          "humidity": 43,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 23,
          "uv_index": 2,
          "wind_angle": 139,
          "wind_dir": "se",
          "wind_gust": 2.2,
          "wind_speed": 1.2
        },
        {
          "hour": "12",
          "hour_ts": 1726650000,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 23,
          "humidity": 38,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 24,
          "uv_index": 3,
          "wind_angle": 134,
          "wind_dir": "se",
          "wind_gust": 2.1,
          "wind_speed": 1.1
        },
        {
          "hour": "13",
          "hour_ts": 1726653600,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 24,
          "humidity": 32,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 25,
          "uv_index": 3,
          "wind_angle": 143,
          "wind_dir": "se",
          "wind_gust": 1.4,
          "wind_speed": 1.3
        },
        {
          "hour": "14",
          "hour_ts": 1726657200,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 23,
          "humidity": 30,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 25,
          "uv_index": 2,
          "wind_angle": 124,
          "wind_dir": "se",
          "wind_gust": 1.1,
          "wind_speed": 1.1
        },
        {
          "hour": "15",
          "hour_ts": 1726660800,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 25,
          "humidity": 30,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_mm": 0,
          "prec_period": 60,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 26,
          "uv_index": 2,
          "wind_angle": 127,
          "wind_dir": "se",
          "wind_gust": 2,
          "wind_speed": 1
        },
        {
          "hour": "16",
          "hour_ts": 1726664400,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 23,
          "humidity": 30,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_mm": 0,
          "prec_period": 60,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 25,
          "uv_index": 1,
          "wind_angle": 301,
          "wind_dir": "nw",
          "wind_gust": 2.1,
          "wind_speed": 1.1
        },
        {
          "hour": "17",
          "hour_ts": 1726668000,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 23,
          "humidity": 35,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_mm": 0,
          "prec_period": 60,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 24,
          "uv_index": 0,
          "wind_angle": 315,
          "wind_dir": "nw",
          "wind_gust": 2,
          "wind_speed": 1
        },
        {
          "hour": "18",
          "hour_ts": 1726671600,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 22,
          "humidity": 39,
          "icon": "skc_d",
          "is_thunder": false,
          "prec_mm": 0,
          "prec_period": 60,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 23,
          "uv_index": 0,
          "wind_angle": 298,
          "wind_dir": "nw",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "19",
          "hour_ts": 1726675200,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 19,
          "humidity": 44,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_mm": 0,
          "prec_period": 60,
          "prec_prob": 0,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 20,
          "uv_index": 0,
          "wind_angle": 279,
          "wind_dir": "w",
          "wind_gust": 1.8,
          "wind_speed": 0.8
        },
        {
          "hour": "20",
          "hour_ts": 1726678800,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 17,
          "humidity": 49,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 18,
          "uv_index": 0,
          "wind_angle": 248,
          "wind_dir": "w",
          "wind_gust": 1.7,
          "wind_speed": 0.7
        },
        {
          "hour": "21",
          "hour_ts": 1726682400,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 15,
          "humidity": 55,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 16,
          "uv_index": 0,
          "wind_angle": 241,
          "wind_dir": "sw",
          "wind_gust": 1.6,
          "wind_speed": 0.6
        },
        {
          "hour": "22",
          "hour_ts": 1726686000,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 13,
          "humidity": 62,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 14,
          "uv_index": 0,
          "wind_angle": 226,
          "wind_dir": "sw",
          "wind_gust": 1.9,
          "wind_speed": 0.9
        },
        {
          "hour": "23",
          "hour_ts": 1726689600,
          "cloudness": 0,
          "condition": "clear",
          "feels_like": 13,
          "humidity": 66,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 14,
          "uv_index": 0,
          "wind_angle": 257,
          "wind_dir": "w",
          "wind_gust": 1.9,
          "wind_speed": 0.9
        }
      ]
    },
    {
      "date": "2024-09-19",
      "date_ts": 1726693200,
      "week": 38,
      "sunrise": "06:09",
      "sunset": "18:37",
      "rise_begin": "05:32",
      "set_end": "19:15",
      "moon_code": 1,
      "moon_text": "moon-code-1",
      "parts": {
        "day": {
          "daytime": "d",
          "_source": "12,13,14,15,16,17",
          "cloudness": 1,
          "condition": "overcast",
          "humidity": 47,
          "icon": "ovc",
          "polar": false,
          "prec_period": 360,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 21,
          "temp_max": 22,
          "temp_min": 20,
          "feels_like": 18,
          "uv_index": 3,
          "wind_angle": 315,
          "wind_dir": "nw",
          "wind_gust": 9.6,
          "wind_speed": 4.5
        },
        "day_short": {
          "daytime": "d",
          "_source": "6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21",
          "cloudness": 1,
          "condition": "overcast",
          "humidity": 53,
          "icon": "ovc",
          "polar": false,
          "prec_period": 960,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 22,
          "temp_min": 11,
          "feels_like": 15,
          "uv_index": 3,
          "wind_angle": 315,
          "wind_dir": "nw",
          "wind_gust": 9.6,
          "wind_speed": 4.5
        },
        "evening": {
          "daytime": "n",
          "_source": "18,19,20,21",
          "cloudness": 1,
          "condition": "overcast",
          "humidity": 56,
          "icon": "ovc",
          "polar": false,
          "prec_period": 240,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 17,
          "temp_max": 18,
          "temp_min": 15,
          "feels_like": 15,
          "uv_index": 0,
          "wind_angle": 0,
          "wind_dir": "n",
          "wind_gust": 7.6,
          "wind_speed": 2.7
        },
        "morning": {
          "daytime": "d",
          "_source": "6,7,8,9,10,11",
          "cloudness": 1,
          "condition": "overcast",
          "humidity": 58,
          "icon": "ovc",
          "polar": false,
          "prec_period": 360,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 16,
          "temp_max": 20,
          "temp_min": 11,
          "feels_like": 13,
          "uv_index": 1,
          "wind_angle": 270,
          "wind_dir": "w",
          "wind_gust": 8.1,
          "wind_speed": 2.9
        },
        "night": {
          "daytime": "n",
          "_source": "22,23,0,1,2,3,4,5",
          "cloudness": 0.5,
          "condition": "cloudy",
          "humidity": 66,
          "icon": "bkn_n",
          "polar": false,
          "prec_period": 480,
          "prec_strength": 0,
          "prec_type": 0,
          "temp_avg": 13,
          "temp_max": 14,
          "temp_min": 11,
          "feels_like": 11,
          "uv_index": 0,
          "wind_angle": 270,
          "wind_dir": "w",
          "wind_gust": 2.4,
          "wind_speed": 1.4
        },
        "night_short": {
          "daytime": "n",
          "_source": "22,23,0,1,2,3,4,5",
          "cloudness": 0.5,
          "condition": "cloudy",
          "humidity": 66,
          "icon": "bkn_n",
          "polar": false,
          "prec_period": 480,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 11,
          "feels_like": 11,
          "uv_index": 0,
          "wind_angle": 270,
          "wind_dir": "w",
          "wind_gust": 2.4,
          "wind_speed": 1.4
        }
      },
      "hours": [
        {
          "hour": "0",
          "hour_ts": 1726693200,
          "cloudness": 0.25,
          "condition": "partly-cloudy",
          "feels_like": 12,
          "humidity": 68,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 13,
          "uv_index": 0,
          "wind_angle": 264,
          "wind_dir": "w",
          "wind_gust": 1.7,
          "wind_speed": 0.7
        },
        {
          "hour": "1",
          "hour_ts": 1726696800,
          "cloudness": 0.5,
          "condition": "cloudy",
          "feels_like": 10,
          "humidity": 67,
          "icon": "bkn_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 244,
          "wind_dir": "sw",
          "wind_gust": 1.9,
          "wind_speed": 0.9
        },
        {
          "hour": "2",
          "hour_ts": 1726700400,
          "cloudness": 0.25,
          "condition": "partly-cloudy",
          "feels_like": 10,
          "humidity": 65,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 256,
          "wind_dir": "w",
          "wind_gust": 2,
          "wind_speed": 1
        },
        {
          "hour": "3",
          "hour_ts": 1726704000,
          "cloudness": 0.5,
          "condition": "cloudy",
          "feels_like": 9,
          "humidity": 66,
          "icon": "bkn_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 11,
          "uv_index": 0,
          "wind_angle": 257,
          "wind_dir": "w",
          "wind_gust": 2.1,
          "wind_speed": 1.1
        },
        {
          "hour": "4",
          "hour_ts": 1726707600,
          "cloudness": 0.5,
          "condition": "cloudy",
          "feels_like": 10,
          "humidity": 67,
          "icon": "bkn_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 264,
          "wind_dir": "w",
          "wind_gust": 2.3,
          "wind_speed": 1.3
        },
        {
          "hour": "5",
          "hour_ts": 1726711200,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 10,
          "humidity": 67,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 270,
          "wind_dir": "w",
          "wind_gust": 2.4,
          "wind_speed": 1.4
        },
        {
          "hour": "6",
          "hour_ts": 1726714800,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 9,
          "humidity": 69,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 11,
          "uv_index": 0,
          "wind_angle": 271,
          "wind_dir": "w",
          "wind_gust": 2.3,
          "wind_speed": 1.3
        },
        {
          "hour": "7",
          "hour_ts": 1726718400,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 10,
          "humidity": 67,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 12,
          "uv_index": 0,
          "wind_angle": 279,
          "wind_dir": "w",
          "wind_gust": 2.6,
          "wind_speed": 1.6
        },
        {
          "hour": "8",
          "hour_ts": 1726722000,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 12,
          "humidity": 61,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 14,
          "uv_index": 0,
          "wind_angle": 281,
          "wind_dir": "w",
          "wind_gust": 2.9,
          "wind_speed": 1.9
        },
        {
          "hour": "9",
          "hour_ts": 1726725600,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 15,
          "humidity": 51,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 17,
          "uv_index": 1,
          "wind_angle": 285,
          "wind_dir": "w",
          "wind_gust": 4.9,
          "wind_speed": 2.2
        },
        {
          "hour": "10",
          "hour_ts": 1726729200,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 17,
          "humidity": 49,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 19,
          "uv_index": 1,
          "wind_angle": 288,
          "wind_dir": "w",
          "wind_gust": 6.8,
          "wind_speed": 2.7
        },
        {
          "hour": "11",
          "hour_ts": 1726732800,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 18,
          "humidity": 48,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 20,
          "uv_index": 1,
          "wind_angle": 296,
          "wind_dir": "nw",
          "wind_gust": 8.1,
          "wind_speed": 2.9
        },
        {
          "hour": "12",
          "hour_ts": 1726736400,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 18,
          "humidity": 46,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 21,
          "uv_index": 2,
          "wind_angle": 307,
          "wind_dir": "nw",
          "wind_gust": 9.5,
          "wind_speed": 3.4
        },
        {
          "hour": "13",
          "hour_ts": 1726740000,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 19,
          "humidity": 46,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 22,
          "uv_index": 3,
          "wind_angle": 308,
          "wind_dir": "nw",
          "wind_gust": 9.6,
          "wind_speed": 4.2
        },
        {
          "hour": "14",
          "hour_ts": 1726743600,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 19,
          "humidity": 47,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 22,
          "uv_index": 2,
          "wind_angle": 311,
          "wind_dir": "nw",
          "wind_gust": 9.5,
          "wind_speed": 4.4
        },
        {
          "hour": "15",
          "hour_ts": 1726747200,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 18,
          "humidity": 48,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 21,
          "uv_index": 2,
          "wind_angle": 315,
          "wind_dir": "nw",
          "wind_gust": 9.6,
          "wind_speed": 4
        },
        {
          "hour": "16",
          "hour_ts": 1726750800,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 16,
          "humidity": 46,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 20,
          "uv_index": 1,
          "wind_angle": 323,
          "wind_dir": "nw",
          "wind_gust": 9.5,
          "wind_speed": 4.5
        },
        {
          "hour": "17",
          "hour_ts": 1726754400,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 17,
          "humidity": 47,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 20,
          "uv_index": 0,
          "wind_angle": 330,
          "wind_dir": "nw",
          "wind_gust": 9.1,
          "wind_speed": 4
        },
        {
          "hour": "18",
          "hour_ts": 1726758000,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 15,
          "humidity": 48,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 18,
          "uv_index": 0,
          "wind_angle": 338,
          "wind_dir": "n",
          "wind_gust": 7.6,
          "wind_speed": 2.7
        },
        {
          "hour": "19",
          "hour_ts": 1726761600,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 15,
          "humidity": 54,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 17,
          "uv_index": 0,
          "wind_angle": 351,
          "wind_dir": "n",
          "wind_gust": 7,
          "wind_speed": 2.6
        },
        {
          "hour": "20",
          "hour_ts": 1726765200,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 14,
          "humidity": 59,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 16,
          "uv_index": 0,
          "wind_angle": 351,
          "wind_dir": "n",
          "wind_gust": 5.3,
          "wind_speed": 2.4
        },
        {
          "hour": "21",
          "hour_ts": 1726768800,
          "cloudness": 1,
          "condition": "overcast",
          "feels_like": 13,
          "humidity": 63,
          "icon": "ovc",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 15,
          "uv_index": 0,
          "wind_angle": 353,
          "wind_dir": "n",
          "wind_gust": 2.9,
          "wind_speed": 1.7
        },
        {
          "hour": "22",
          "hour_ts": 1726772400,
          "cloudness": 0.25,
          "condition": "partly-cloudy",
          "feels_like": 12,
          "humidity": 67,
          "icon": "skc_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 14,
          "uv_index": 0,
          "wind_angle": 358,
          "wind_dir": "n",
          "wind_gust": 2.2,
          "wind_speed": 1.8
        },
        {
          "hour": "23",
          "hour_ts": 1726776000,
          "cloudness": 0.5,
          "condition": "cloudy",
          "feels_like": 13,
          "humidity": 69,
          "icon": "bkn_n",
          "is_thunder": false,
          "prec_period": 60,
          "prec_strength": 0,
          "prec_type": 0,
          "temp": 14,
          "uv_index": 0,
          "wind_angle": 359,
          "wind_dir": "n",
          "wind_gust": 2.6,
          "wind_speed": 1.6
        }
      ]
    }
  ]
}
)YW";


#endif

ControllerWeather::ControllerWeather(const char* name):
                    Controller(name), _doc() {
    _updateTimeInSec = 20 * 60;
    
    isValid = false;
    weatherDescription.reserve(128);
    weatherUrlIcon.reserve(128);
    weatherWindSpeed.reserve(16);
    weatherWindType.reserve(64);
    weatherHumidity.reserve(16);
    weatherPressure.reserve(16);
    weatherTemperature.reserve(16);
    payload.reserve(8192);
}

InitResponse_t ControllerWeather::OnInit() {
    return OnInitResultStart;
}

IterationCode_t ControllerWeather::OnIteration() {
    if (!WiFi.isConnected()) {
        isValid = false;
        LOGN("%s::isValid, %d", _name, isValid);
        return IterationCode_t::Ok;   
    }
#if !defined(WEATHER_STUB)
    httpClient.begin("https://api.weather.yandex.ru/v2/forecast?lat=55.783230&lon=37.473060");
    httpClient.addHeader("X-Yandex-Weather-Key", "837f22c6-d139-4aa2-8579-e3712309b744");
    isValid = httpClient.GET() == HTTP_CODE_OK;
    if (isValid) {
        payload = httpClient.getString();
        isValid = !payload.isEmpty();
    }
    httpClient.setReuse(true);
#endif
#if defined(WEATHER_STUB)
    isValid = true;
    payload = weather_stub;
#endif
    if (isValid) {
        isValid = parseWeatherInfo(httpClient, payload);
    }

    LOGN("%s::isValid, %d", _name, isValid);
    return IterationCode_t::Ok;
}

uint16_t ControllerWeather::ColorToRGB565(const uint8_t r, const uint8_t g, const uint8_t b) {
    return (uint16_t)(((r & 0b11111000) << 8) | ((g & 0b11111100) << 3) | (b >> 3));
}

bool ControllerWeather::parseWeatherInfo(HTTPClient& client, String& payload) {
    char* pstr = payload.begin();
    DeserializationError error = deserializeJson(_doc, pstr);
    if (error) {
        LOGN("Failed to read json, using default configuration");
        return false;
    }
    iconFileName.clear();
    weatherDescription = _doc["current"]["condition"]["text"].as<String>();
    weatherTemperature = _doc["current"]["temp_c"].as<String>();
    weatherHumidity = _doc["current"]["humidity"].as<String>();
    weatherPressure = String(_doc["current"]["pressure_mb"].as<float>() * 0.750062, 1);
    weatherWindSpeed = _doc["current"]["wind_mph"].as<String>();
    weatherWindType =_doc["current"]["wind_dir"].as<String>();
    weatherUrlIcon = _doc["current"]["condition"]["icon"].as<String>();

    if (!weatherTemperature.isEmpty()) {
        weatherTemperature += "°";
        if (isdigit(weatherTemperature[0])) {
            weatherTemperature = "+" + weatherTemperature;
        }
    }
    // //cdn.weatherapi.com/weather/64x64/night/311.png
    // //cdn.weatherapi.com/weather/64x64/day/311.png
    if (!weatherUrlIcon.isEmpty()) {
        weatherUrlIcon = "https:" + weatherUrlIcon;
        int pos = weatherUrlIcon.lastIndexOf('/');
        if (pos != 1) {
            if (weatherUrlIcon.indexOf("night") != -1) {
                iconFileName = "/icon/night" + weatherUrlIcon.substring(pos);
            } else if (weatherUrlIcon.indexOf("day") != -1) {
                iconFileName = "/icon/day" + weatherUrlIcon.substring(pos);
            } else {
                iconFileName.clear();
            }
        }
        if (!SPIFFS.exists(iconFileName)) {
            if (client.begin(weatherUrlIcon)) {
                int code = client.GET();
                if (code == HTTP_CODE_OK) {
                    File f = SPIFFS.open(iconFileName, "w");
                    if (f) {
                        client.writeToStream(&f);
                        f.close();
                    }
                }
                client.end();
            }
        }
    }    
    LOGN("%s::weatherDescription, %s", _name, weatherDescription.c_str());
    LOGN("%s::weatherTemperature, %s", _name, weatherTemperature.c_str());
    LOGN("%s::weatherPressure, %s", _name, weatherPressure.c_str());
    LOGN("%s::weatherHumidity, %s", _name, weatherHumidity.c_str());
    LOGN("%s::weatherWindSpeed, %s", _name, weatherWindSpeed.c_str());
    LOGN("%s::weatherWindType, %s", _name, weatherWindType.c_str());
    LOGN("%s::weatherUrlIcon, %s", _name, weatherUrlIcon.c_str());
    LOGN("%s::iconFileName, %s", _name, iconFileName.c_str());
    LOGN("%s::windFileName, %s", _name, windFileName.c_str());

    return true;
}
